spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.18.118:3306/book_system
    username: root
    password: root
  #配置于template中的页面需添加thymeleaf前端解析器
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #禁用缓存
    encoding: UTF-8

server:
  servlet:
    session:
      timeout: 259200m #session过期时间3天
  port: 18080

mybatis:
  type-aliases-package: com.example.booksystem.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #默认即开启了驼峰命名
